name: Preprocessing-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATA: "./dataset_raw/water_potability_raw.csv"

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.12"

      # Install MLflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      # Run Preprocessing Script
      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_Anggun-Sulis-Setyawan.py \
            --input ./dataset_raw/water_potability_raw.csv \
            --output ./preprocessing/water_potability_preprocessing.csv
            
      # Save pipeline to GitHub Repository
      - name: Save pipeline to repository
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add preprocessing/water_potability_preprocessing.csv
          git add preprocessing/preprocessing_pipeline.joblib || echo "No pipeline found"
          git commit -m "Add preprocessor and preprocessed data from CI run" || echo "No changes to commit"
          git push origin main